# Generated by Django 3.2.5 on 2021-11-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryosai_2021', '0004_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
