# Generated by Django 3.2.5 on 2021-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryosai_2021', '0005_alter_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='body',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
